const capabilities = {
    maxInstances: 1,
    browserName: '',
    acceptInsecureCerts: false,
    appiumVersion: '1.20.0',
    platformName: 'Android',
    platformVersion: '10',
    deviceName: 'Galaxy Tab S4',
    app: 'lt://APP100161621639584120475866',
    automationName: 'UiAutomator2',
    uiautomator2ServerLaunchTimeout: 300000,
    uiautomator2ServerInstallTimeout: 300000,
    uiautomator2ServerReadTimeout: 300000,
    visual: true,
    console: true,
    deviceOrientation: 'PORTRAIT',
    build: 'new-12',
    isRealMobile: true,
};
exports.capabilities = capabilities;